//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string ProductName_en { get; set; }
        public string ProductName_ar { get; set; }
        public int Qty { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> Date_Entry { get; set; }
        public Nullable<double> Price { get; set; }
        public string Code { get; set; }
    }
}
